name: 📚 Documentation
description: Report missing, unclear, or incorrect documentation
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
projects: ["narrowstacks/1"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve Dorkroom's documentation! Clear documentation helps everyone in the analog photography community.

  - type: dropdown
    id: documentation-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs attention?
      options:
        - User Guide/Tutorial
        - Calculator Instructions
        - API Documentation
        - Code Documentation
        - Setup/Installation Guide
        - Contributing Guidelines
        - README Updates
        - Mathematical Formulas
        - Photography Concepts
        - Troubleshooting Guide
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What's the problem with the documentation?
      options:
        - Missing Documentation
        - Incorrect Information
        - Unclear/Confusing Content
        - Outdated Information
        - Broken Links
        - Poor Organization
        - Missing Examples
        - Translation Issue
        - Accessibility Issue
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue located?
      placeholder: |
        - URL: [if web documentation]
        - File path: [if code documentation]
        - Section/Page: [specific location]
        - Calculator: [which calculator's docs]
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: What does the current documentation say? (copy/paste if possible)
      placeholder: Quote the current content that needs improvement
    validations:
      required: false

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe the problem with the current documentation
      placeholder: |
        What specifically is wrong, missing, or unclear?
        - What confused you?
        - What information is missing?
        - What would help other users?
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How would you improve this documentation?
      placeholder: |
        Provide specific suggestions:
        - Corrected text
        - Additional information to include
        - Better organization
        - Examples or clarifications needed
    validations:
      required: true

  - type: dropdown
    id: target-audience
    attributes:
      label: Target Audience
      description: Who would benefit from this documentation improvement?
      multiple: true
      options:
        - New Dorkroom Users
        - Experienced Darkroom Workers
        - Developers/Contributors
        - Photography Students
        - Alternative Process Photographers
        - Digital Negative Users
        - Mobile Users
        - All Users
    validations:
      required: true

  - type: textarea
    id: photography-context
    attributes:
      label: Photography Context
      description: What photography knowledge or context should be included?
      placeholder: |
        - Photography concepts to explain
        - Darkroom techniques to reference
        - Equipment or materials mentioned
        - Skill level assumptions
    validations:
      required: false

  - type: textarea
    id: examples-needed
    attributes:
      label: Examples Needed
      description: What examples would make this documentation clearer?
      placeholder: |
        - Step-by-step examples
        - Real-world scenarios
        - Screenshots or diagrams
        - Sample calculations
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this documentation improvement?
      options:
        - Low - Minor improvement
        - Medium - Would help several users
        - High - Confusing or blocking users
        - Critical - Incorrect information that could cause problems
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        - Related documentation that needs similar updates
        - Links to reference materials
        - User feedback or questions you've seen
        - Screenshots of the issue
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have checked that this documentation issue hasn't been reported before
          required: true
        - label: I have provided specific suggestions for improvement
          required: true
        - label: This improvement would help other users in the community
          required: true
