// Mock debugLogger for tests
export const debugLog = jest.fn();
export const debugWarn = jest.fn();
export const debugError = jest.fn();
export const debugLogTiming = jest.fn();
export const startContinuousFPSMonitoring = jest.fn();
export const stopContinuousFPSMonitoring = jest.fn();
export const debugLogPerformance = jest.fn();
export const debugLogAnimationFrame = jest.fn();
export const debugLogMemory = jest.fn();
