/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StopsRouteImport } from './routes/stops'
import { Route as SplitGradeRouteImport } from './routes/split-grade'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResizeRouteImport } from './routes/resize'
import { Route as ReciprocityRouteImport } from './routes/reciprocity'
import { Route as InfobaseRouteImport } from './routes/infobase'
import { Route as ExposureRouteImport } from './routes/exposure'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as BorderRouteImport } from './routes/border'
import { Route as IndexRouteImport } from './routes/index'

const StopsRoute = StopsRouteImport.update({
  id: '/stops',
  path: '/stops',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitGradeRoute = SplitGradeRouteImport.update({
  id: '/split-grade',
  path: '/split-grade',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResizeRoute = ResizeRouteImport.update({
  id: '/resize',
  path: '/resize',
  getParentRoute: () => rootRouteImport,
} as any)
const ReciprocityRoute = ReciprocityRouteImport.update({
  id: '/reciprocity',
  path: '/reciprocity',
  getParentRoute: () => rootRouteImport,
} as any)
const InfobaseRoute = InfobaseRouteImport.update({
  id: '/infobase',
  path: '/infobase',
  getParentRoute: () => rootRouteImport,
} as any)
const ExposureRoute = ExposureRouteImport.update({
  id: '/exposure',
  path: '/exposure',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const BorderRoute = BorderRouteImport.update({
  id: '/border',
  path: '/border',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/border': typeof BorderRoute
  '/development': typeof DevelopmentRoute
  '/exposure': typeof ExposureRoute
  '/infobase': typeof InfobaseRoute
  '/reciprocity': typeof ReciprocityRoute
  '/resize': typeof ResizeRoute
  '/settings': typeof SettingsRoute
  '/split-grade': typeof SplitGradeRoute
  '/stops': typeof StopsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/border': typeof BorderRoute
  '/development': typeof DevelopmentRoute
  '/exposure': typeof ExposureRoute
  '/infobase': typeof InfobaseRoute
  '/reciprocity': typeof ReciprocityRoute
  '/resize': typeof ResizeRoute
  '/settings': typeof SettingsRoute
  '/split-grade': typeof SplitGradeRoute
  '/stops': typeof StopsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/border': typeof BorderRoute
  '/development': typeof DevelopmentRoute
  '/exposure': typeof ExposureRoute
  '/infobase': typeof InfobaseRoute
  '/reciprocity': typeof ReciprocityRoute
  '/resize': typeof ResizeRoute
  '/settings': typeof SettingsRoute
  '/split-grade': typeof SplitGradeRoute
  '/stops': typeof StopsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/border'
    | '/development'
    | '/exposure'
    | '/infobase'
    | '/reciprocity'
    | '/resize'
    | '/settings'
    | '/split-grade'
    | '/stops'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/border'
    | '/development'
    | '/exposure'
    | '/infobase'
    | '/reciprocity'
    | '/resize'
    | '/settings'
    | '/split-grade'
    | '/stops'
  id:
    | '__root__'
    | '/'
    | '/border'
    | '/development'
    | '/exposure'
    | '/infobase'
    | '/reciprocity'
    | '/resize'
    | '/settings'
    | '/split-grade'
    | '/stops'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BorderRoute: typeof BorderRoute
  DevelopmentRoute: typeof DevelopmentRoute
  ExposureRoute: typeof ExposureRoute
  InfobaseRoute: typeof InfobaseRoute
  ReciprocityRoute: typeof ReciprocityRoute
  ResizeRoute: typeof ResizeRoute
  SettingsRoute: typeof SettingsRoute
  SplitGradeRoute: typeof SplitGradeRoute
  StopsRoute: typeof StopsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stops': {
      id: '/stops'
      path: '/stops'
      fullPath: '/stops'
      preLoaderRoute: typeof StopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split-grade': {
      id: '/split-grade'
      path: '/split-grade'
      fullPath: '/split-grade'
      preLoaderRoute: typeof SplitGradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resize': {
      id: '/resize'
      path: '/resize'
      fullPath: '/resize'
      preLoaderRoute: typeof ResizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reciprocity': {
      id: '/reciprocity'
      path: '/reciprocity'
      fullPath: '/reciprocity'
      preLoaderRoute: typeof ReciprocityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infobase': {
      id: '/infobase'
      path: '/infobase'
      fullPath: '/infobase'
      preLoaderRoute: typeof InfobaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exposure': {
      id: '/exposure'
      path: '/exposure'
      fullPath: '/exposure'
      preLoaderRoute: typeof ExposureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/border': {
      id: '/border'
      path: '/border'
      fullPath: '/border'
      preLoaderRoute: typeof BorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BorderRoute: BorderRoute,
  DevelopmentRoute: DevelopmentRoute,
  ExposureRoute: ExposureRoute,
  InfobaseRoute: InfobaseRoute,
  ReciprocityRoute: ReciprocityRoute,
  ResizeRoute: ResizeRoute,
  SettingsRoute: SettingsRoute,
  SplitGradeRoute: SplitGradeRoute,
  StopsRoute: StopsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
